// Canonical Dragodinde color/breed DAG — extracted & verified from
// https://www.dofuspourlesnoobs.com/les-dragodindes.html (section V).
// 66 reproducible colors, Gen 1–10. Each non-base color = exactly 2 parent colors.
// DO NOT hand-edit recipes; regenerate from source if the game changes.

export interface ColorDef {
  readonly name: string;
  readonly gen: number;
  readonly bonus: ReadonlyArray<string>; // raw bonus lines (incl. '400 Vitalité')
  readonly parents: readonly [string, string] | null; // null => base (captured)
}

export const COLORS: ReadonlyArray<ColorDef> = [
  { name: "Amande", gen: 1, bonus: ["400 Vitalité", "1700 Initiative"], parents: null },
  { name: "Dorée", gen: 1, bonus: ["400 Vitalité", "2 Invocations"], parents: null },
  { name: "Rousse", gen: 1, bonus: ["400 Vitalité", "60 Soins"], parents: null },
  { name: "Amande et Rousse", gen: 2, bonus: ["400 Vitalité", "60 Soins", "1200 Initiative"], parents: ["Amande", "Rousse"] },
  { name: "Dorée et Rousse", gen: 2, bonus: ["400 Vitalité", "1 Invocation", "45 Soins"], parents: ["Dorée", "Rousse"] },
  { name: "Amande et Dorée", gen: 2, bonus: ["400 Vitalité", "1 Invocation", "1200 Initiative"], parents: ["Amande", "Dorée"] },
  { name: "Ebène", gen: 3, bonus: ["400 Vitalité", "120 Agilité"], parents: ["Amande et Dorée", "Dorée et Rousse"] },
  { name: "Indigo", gen: 3, bonus: ["400 Vitalité", "120 Chance"], parents: ["Amande et Dorée", "Amande et Rousse"] },
  { name: "Indigo et Rousse", gen: 4, bonus: ["400 Vitalité", "90 Chance", "45 Soins"], parents: ["Indigo", "Rousse"] },
  { name: "Ebène et Rousse", gen: 4, bonus: ["400 Vitalité", "90 Agilité", "45 Soins"], parents: ["Ebène", "Rousse"] },
  { name: "Amande et Indigo", gen: 4, bonus: ["400 Vitalité", "90 Chance", "1200 Initiative"], parents: ["Amande", "Indigo"] },
  { name: "Amande et Ebène", gen: 4, bonus: ["400 Vitalité", "120 Agilité", "1200 Initiative"], parents: ["Amande", "Ebène"] },
  { name: "Dorée et Indigo", gen: 4, bonus: ["400 Vitalité", "90 Chance", "1 Invocation"], parents: ["Dorée", "Indigo"] },
  { name: "Dorée et Ebène", gen: 4, bonus: ["400 Vitalité", "90 Agilité", "1 Invocation"], parents: ["Dorée", "Ebène"] },
  { name: "Ebène et Indigo", gen: 4, bonus: ["400 Vitalité", "90 Chance", "90 Agilité"], parents: ["Ebène", "Indigo"] },
  { name: "Pourpre", gen: 5, bonus: ["400 Vitalité", "120 Force"], parents: ["Ebène et Indigo", "Amande et Rousse"] },
  { name: "Orchidée", gen: 5, bonus: ["400 Vitalité", "120 Intelligence"], parents: ["Ebène et Indigo", "Dorée et Rousse"] },
  { name: "Pourpre et Rousse", gen: 6, bonus: ["400 Vitalité", "90 Force", "45 Soins"], parents: ["Pourpre", "Rousse"] },
  { name: "Orchidée et Rousse", gen: 6, bonus: ["400 Vitalité", "90 Intelligence", "45 Soins"], parents: ["Orchidée", "Rousse"] },
  { name: "Amande et Pourpre", gen: 6, bonus: ["400 Vitalité", "90 Force", "1200 Initiative"], parents: ["Amande", "Pourpre"] },
  { name: "Amande et Orchidée", gen: 6, bonus: ["400 Vitalité", "90 Intelligence", "1200 Initiative"], parents: ["Amande", "Orchidée"] },
  { name: "Dorée et Pourpre", gen: 6, bonus: ["400 Vitalité", "90 Force", "1 Invocation"], parents: ["Dorée", "Pourpre"] },
  { name: "Dorée et Orchidée", gen: 6, bonus: ["400 Vitalité", "90 Intelligence", "1 Invocation"], parents: ["Dorée", "Orchidée"] },
  { name: "Indigo et Pourpre", gen: 6, bonus: ["400 Vitalité", "90 Force", "90 Chance"], parents: ["Indigo", "Pourpre"] },
  { name: "Indigo et Orchidée", gen: 6, bonus: ["400 Vitalité", "90 Intelligence", "90 Chance"], parents: ["Indigo", "Orchidée"] },
  { name: "Ebène et Pourpre", gen: 6, bonus: ["400 Vitalité", "90 Force", "90 Agilité"], parents: ["Ebène", "Pourpre"] },
  { name: "Ebène et Orchidée", gen: 6, bonus: ["400 Vitalité", "90 Intelligence", "90 Agilité"], parents: ["Ebène", "Orchidée"] },
  { name: "Orchidée et Pourpre", gen: 6, bonus: ["400 Vitalité", "90 Force", "90 Intelligence"], parents: ["Orchidée", "Pourpre"] },
  { name: "Ivoire", gen: 7, bonus: ["400 Vitalité", "90 Puissance"], parents: ["Orchidée et Pourpre", "Indigo et Pourpre"] },
  { name: "Turquoise", gen: 7, bonus: ["400 Vitalité", "90 Prospection"], parents: ["Orchidée et Pourpre", "Ebène et Orchidée"] },
  { name: "Ivoire et Rousse", gen: 8, bonus: ["400 Vitalité", "70 Puissance", "45 Soins"], parents: ["Ivoire", "Rousse"] },
  { name: "Turquoise et Rousse", gen: 8, bonus: ["400 Vitalité", "45 Soins", "70 Prospection"], parents: ["Turquoise", "Rousse"] },
  { name: "Amande et Ivoire", gen: 8, bonus: ["400 Vitalité", "70 Puissance", "1200 Initiative"], parents: ["Amande", "Ivoire"] },
  { name: "Amande et Turquoise", gen: 8, bonus: ["400 Vitalité", "70 Prospection", "1200 Initiative"], parents: ["Amande", "Turquoise"] },
  { name: "Dorée et Ivoire", gen: 8, bonus: ["400 Vitalité", "70 Puissance", "1 Invocation"], parents: ["Dorée", "Ivoire"] },
  { name: "Dorée et Turquoise", gen: 8, bonus: ["400 Vitalité", "1 Invocation", "70 Prospection"], parents: ["Dorée", "Turquoise"] },
  { name: "Indigo et Ivoire", gen: 8, bonus: ["400 Vitalité", "90 Chance", "70 Puissance"], parents: ["Indigo", "Ivoire"] },
  { name: "Indigo et Turquoise", gen: 8, bonus: ["400 Vitalité", "90 Chance", "70 Prospection"], parents: ["Indigo", "Turquoise"] },
  { name: "Ebène et Ivoire", gen: 8, bonus: ["400 Vitalité", "90 Agilité", "70 Puissance"], parents: ["Ebène", "Ivoire"] },
  { name: "Ebène et Turquoise", gen: 8, bonus: ["400 Vitalité", "90 Agilité", "70 Prospection"], parents: ["Ebène", "Turquoise"] },
  { name: "Ivoire et Pourpre", gen: 8, bonus: ["400 Vitalité", "90 Force", "70 Puissance"], parents: ["Ivoire", "Pourpre"] },
  { name: "Turquoise et Pourpre", gen: 8, bonus: ["400 Vitalité", "90 Force", "70 Prospection"], parents: ["Turquoise", "Pourpre"] },
  { name: "Ivoire et Orchidée", gen: 8, bonus: ["400 Vitalité", "90 Intelligence", "70 Puissance"], parents: ["Ivoire", "Orchidée"] },
  { name: "Turquoise et Orchidée", gen: 8, bonus: ["400 Vitalité", "90 Intelligence", "70 Prospection"], parents: ["Turquoise", "Orchidée"] },
  { name: "Ivoire et Turquoise", gen: 8, bonus: ["400 Vitalité", "70 Puissance", "70 Prospection"], parents: ["Ivoire", "Turquoise"] },
  { name: "Emeraude", gen: 9, bonus: ["400 Vitalité", "14% Critique"], parents: ["Ivoire et Turquoise", "Ivoire et Pourpre"] },
  { name: "Prune", gen: 9, bonus: ["400 Vitalité", "2 Portée"], parents: ["Ivoire et Turquoise", "Turquoise et Orchidée"] },
  { name: "Emeraude et Rousse", gen: 10, bonus: ["400 Vitalité", "10% Critique", "45 Soins"], parents: ["Emeraude", "Rousse"] },
  { name: "Prune et Rousse", gen: 10, bonus: ["400 Vitalité", "1 Portée", "45 Soins"], parents: ["Prune", "Rousse"] },
  { name: "Amande et Emeraude", gen: 10, bonus: ["400 Vitalité", "10% Critique", "1200 Initiative"], parents: ["Amande", "Emeraude"] },
  { name: "Prune et Amande", gen: 10, bonus: ["400 Vitalité", "1 Portée", "1200 Initiative"], parents: ["Prune", "Amande"] },
  { name: "Dorée et Emeraude", gen: 10, bonus: ["400 Vitalité", "10% Critique", "1 Invocation"], parents: ["Dorée", "Emeraude"] },
  { name: "Prune et Dorée", gen: 10, bonus: ["400 Vitalité", "1 Portée", "1 Invocation"], parents: ["Prune", "Dorée"] },
  { name: "Emeraude et Indigo", gen: 10, bonus: ["400 Vitalité", "90 Chance", "10% Critique"], parents: ["Emeraude", "Indigo"] },
  { name: "Prune et Indigo", gen: 10, bonus: ["400 Vitalité", "90 Chance", "1 Portée"], parents: ["Prune", "Indigo"] },
  { name: "Ebène et Emeraude", gen: 10, bonus: ["400 Vitalité", "90 Agilité", "10% Critique"], parents: ["Ebène", "Emeraude"] },
  { name: "Prune et Ebène", gen: 10, bonus: ["400 Vitalité", "90 Agilité", "1 Portée"], parents: ["Prune", "Ebène"] },
  { name: "Emeraude et Pourpre", gen: 10, bonus: ["400 Vitalité", "90 Force", "10% Critique"], parents: ["Emeraude", "Pourpre"] },
  { name: "Prune et Pourpre", gen: 10, bonus: ["400 Vitalité", "90 Force", "1 Portée"], parents: ["Prune", "Pourpre"] },
  { name: "Emeraude et Orchidée", gen: 10, bonus: ["400 Vitalité", "90 Intelligence", "10% Critique"], parents: ["Emeraude", "Orchidée"] },
  { name: "Prune et Orchidée", gen: 10, bonus: ["400 Vitalité", "90 Intelligence", "1 Portée"], parents: ["Prune", "Orchidée"] },
  { name: "Emeraude et Ivoire", gen: 10, bonus: ["400 Vitalité", "70 Puissance", "10% Critique"], parents: ["Emeraude", "Ivoire"] },
  { name: "Prune et Ivoire", gen: 10, bonus: ["400 Vitalité", "70 Puissance", "1 Portée"], parents: ["Prune", "Ivoire"] },
  { name: "Emeraude et Turquoise", gen: 10, bonus: ["400 Vitalité", "10% Critique", "70 Prospection"], parents: ["Emeraude", "Turquoise"] },
  { name: "Prune et Turquoise", gen: 10, bonus: ["400 Vitalité", "1 Portée", "70 Prospection"], parents: ["Prune", "Turquoise"] },
  { name: "Prune et Emeraude", gen: 10, bonus: ["400 Vitalité", "10% Critique", "1 Portée"], parents: ["Prune", "Emeraude"] },
];

export const COLOR_BY_NAME: ReadonlyMap<string, ColorDef> = new Map(COLORS.map((c) => [c.name, c]));
export const BASE_COLORS: ReadonlyArray<string> = COLORS.filter((c) => !c.parents).map((c) => c.name);
// Sink = never used as an ingredient => must be bred explicitly (not a byproduct of anything).
export const SINK_COLORS: ReadonlyArray<string> = [
  "Indigo et Rousse",
  "Ebène et Rousse",
  "Amande et Indigo",
  "Amande et Ebène",
  "Dorée et Indigo",
  "Dorée et Ebène",
  "Pourpre et Rousse",
  "Orchidée et Rousse",
  "Amande et Pourpre",
  "Amande et Orchidée",
  "Dorée et Pourpre",
  "Dorée et Orchidée",
  "Indigo et Orchidée",
  "Ebène et Pourpre",
  "Ivoire et Rousse",
  "Turquoise et Rousse",
  "Amande et Ivoire",
  "Amande et Turquoise",
  "Dorée et Ivoire",
  "Dorée et Turquoise",
  "Indigo et Ivoire",
  "Indigo et Turquoise",
  "Ebène et Ivoire",
  "Ebène et Turquoise",
  "Turquoise et Pourpre",
  "Ivoire et Orchidée",
  "Emeraude et Rousse",
  "Prune et Rousse",
  "Amande et Emeraude",
  "Prune et Amande",
  "Dorée et Emeraude",
  "Prune et Dorée",
  "Emeraude et Indigo",
  "Prune et Indigo",
  "Ebène et Emeraude",
  "Prune et Ebène",
  "Emeraude et Pourpre",
  "Prune et Pourpre",
  "Emeraude et Orchidée",
  "Prune et Orchidée",
  "Emeraude et Ivoire",
  "Prune et Ivoire",
  "Emeraude et Turquoise",
  "Prune et Turquoise",
  "Prune et Emeraude",
];
